# Generated by Django 3.0.7 on 2021-03-16 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qnA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=255)),
                ('is_seen', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_answer', models.BooleanField(default=False)),
                ('is_followed_question', models.BooleanField(default=False)),
                ('is_requested_question', models.BooleanField(default=False)),
                ('is_following_user_questions', models.BooleanField(default=False)),
                ('is_following_user_answers', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_from_people', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notif_question', to='qnA.Question')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_to_people', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
